languageCode: en-us
baseURL: "//gcortesi/"
title: Giacomo Cortesi
paginate: 5
theme: 
  - "hugo-embed-pdf-shortcode"
  - "PaperMod"
enableInlineShortcodes: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

#googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: GiacomoCortesi
  description: ""
  keywords: [Blog, Portfolio, Software Engineering]
  author: Giacomo Cortesi
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: true
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Giacomo Cortesi"
    icon: "images/coding.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "\U0001F44B"
    subtitle: "*What a chance*! Out of billions of web pages you just landed on **Giacomo Cortesi** personal website.  
    **Hi**, I'm a 360° full stack software engineer.
    
    
    Here you can learn more about me."
    imageUrl: "images/dp.png"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "gc"
    buttons:
      - name: Resume
        url: resume
      - name: Blogs
        url: blogs

  # home-info mode
  homeInfoParams:
    Title: "\U0001F44B"
    Content: "*What a chance*! Out of billions of web pages you just landed on **Giacomo Cortesi** personal website.
    Hi, I'm a 360° full stack software engineer.  
    
    
    Here you can learn more about me."

  socialIcons:
    - name: github
      url: "https://github.com/GiacomoCortesi"
    - name: stackoverflow
      url: "https://stackoverflow.com/users/11991497/mello"
    - name: linkedin
      url: "https://www.linkedin.com/in/giacomo-cortesi-81387ab9/"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1
    - identifier: resume
      name: Resume
      url: /resume/
      weight: 1
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
